var a,Cc=Components.classes,Ci=Components.interfaces,Cr=Components.results;var goog=goog||{},goog$global=this,goog$exportPath_=function(b,c,d){b=b.split(".");d=d||goog$global;!(b[0]in d)&&d.execScript&&d.execScript("var "+b[0]);for(var e;b.length&&(e=b.shift());)if(!b.length&&c!==undefined)d[e]=c;else d=d[e]?d[e]:(d[e]={})},goog$getUid=function(b){if(b.hasOwnProperty&&b.hasOwnProperty(goog$UID_PROPERTY_))return b[goog$UID_PROPERTY_];b[goog$UID_PROPERTY_]||(b[goog$UID_PROPERTY_]=++goog$uidCounter_);return b[goog$UID_PROPERTY_]},goog$UID_PROPERTY_="closure_uid_"+Math.floor(Math.random()*
2147483648).toString(36),goog$uidCounter_=0,goog$getHashCode=goog$getUid,goog$bind=function(b,c){var d=c||goog$global;if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,e);return b.apply(d,f)}}else return function(){return b.apply(d,arguments)}},goog$inherits=function(b,c){function d(){}d.prototype=c.prototype;b.superClass_=c.prototype;b.prototype=new d;b.prototype.constructor=b};
Function.prototype.bind=function(b){if(arguments.length>1){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,b);return goog$bind.apply(null,c)}else return goog$bind(this,b)};Function.prototype.inherits=function(b){goog$inherits(this,b)};function G_JSModule(){this.factoryLookup_={};this.categoriesLookup_={}}var G_JSModule$instance_;goog$exportPath_("G_JSModule",G_JSModule,void 0);var G_JSModule$getInstance=function(){return G_JSModule$instance_||(G_JSModule$instance_=new G_JSModule)};G_JSModule.getInstance=G_JSModule$getInstance;G_JSModule.prototype.registerObject=function(b,c,d,e,f){this.registerFactory(new G_JSFactory(Components.ID(b),c,d,e,f))};G_JSModule.prototype.registerObject=G_JSModule.prototype.registerObject;
G_JSModule.prototype.registerFactory=function(b){var c=b.classID.toString();this.factoryLookup_[c]=b;this.categoriesLookup_[c]=b.categories_};G_JSModule.prototype.registerFactory=G_JSModule.prototype.registerFactory;G_JSModule.prototype.registerSelf=function(b,c,d,e){b=b.QueryInterface(Ci.nsIComponentRegistrar);for(var f in this.factoryLookup_){b.registerFactoryLocation(this.factoryLookup_[f].classID,this.factoryLookup_[f].className,this.factoryLookup_[f].contractID,c,d,e);this.factoryLookup_[f].registerCategories()}};
G_JSModule.prototype.registerSelf=G_JSModule.prototype.registerSelf;G_JSModule.prototype.getClassObject=function(b,c){var d=this.factoryLookup_[c.toString()];if(!d)throw Error("Invalid classID {"+c+"}");return d};G_JSModule.prototype.getClassObject=G_JSModule.prototype.getClassObject;G_JSModule.prototype.canUnload=function(){return true};G_JSModule.prototype.canUnload=G_JSModule.prototype.canUnload;
function G_JSFactory(b,c,d,e,f){this.classID=b;this.contractID=c;this.className=d;this.instance_=e;this.categories_=f}G_JSFactory.prototype.registerCategories=function(){if(this.categories_)for(var b=Cc["@mozilla.org/categorymanager;1"].getService(Ci.nsICategoryManager),c=0,d;d=this.categories_[c];c++)b.addCategoryEntry(d,this.className,this.contractID,true,true)};G_JSFactory.prototype.createInstance=function(){return this.instance_};G_JSFactory.prototype.createInstance=G_JSFactory.prototype.createInstance;function GTM_registerMetricsCollector(b,c,d){G_JSModule$getInstance().registerObject(b,"@google.com/toolbar/metrics2/collector;1?name="+c,"Google Toolbar Metrics Collector: "+c,d)}function GTM_getMetricsService(){return Cc["@google.com/toolbar/metrics2/service;1"].getService(Ci.nsIMetricsService2)}function GTM_createPropertyBag(){return Cc["@mozilla.org/hash-property-bag;1"].createInstance(Ci.nsIWritablePropertyBag)}
function GTM_Hasher(b){this.converter_=Cc["@mozilla.org/intl/scriptableunicodeconverter"].createInstance(Ci.nsIScriptableUnicodeConverter);this.converter_.charset="UTF-8";this.hasher_=Cc["@mozilla.org/security/hash;1"].createInstance(Ci.nsICryptoHash);this.cache_={};if(b)this.hashString=this.generateHash_}GTM_Hasher.prototype.hashString=function(b){return this.cache_[b]||(this.cache_[b]=this.generateHash_(b))};
GTM_Hasher.prototype.generateHash_=function(b){b=this.converter_.convertToByteArray(b,{});this.hasher_.init(this.hasher_.MD5);this.hasher_.update(b,b.length);return this.hasher_.finish(true)};function G_Preferences(b,c,d){if(!G_Preferences$getterMap_&&Ci.nsIPrefBranch.PREF_STRING){G_Preferences$getterMap_={};G_Preferences$getterMap_[Ci.nsIPrefBranch.PREF_STRING]="getCharPref";G_Preferences$getterMap_[Ci.nsIPrefBranch.PREF_BOOL]="getBoolPref";G_Preferences$getterMap_[Ci.nsIPrefBranch.PREF_INT]="getIntPref"}this.observers_={};b=b||null;var e=Cc["@mozilla.org/preferences-service;1"].getService(Ci.nsIPrefService);this.prefs_=c?e.getDefaultBranch(b):e.getBranch(b);this.prefs_.QueryInterface(Ci.nsIPrefBranchInternal);
this.noUnicode_=!!d}var G_Preferences$getterMap_;G_Preferences.prototype.debugZone="prefs";var G_Preferences$setterMap_={string:"setCharPref","boolean":"setBoolPref",number:"setIntPref"};a=G_Preferences.prototype;
a.setPref=function(b,c){var d=typeof c;if(d=="number"&&c%1!=0)throw Error("Cannot store non-integer numbers in preferences.");if(d=="string"&&!this.noUnicode_)return this.setUnicodePref(b,c);var e=G_Preferences$setterMap_[d];if(!e)throw Error("Pref datatype {"+d+"} not supported, key: "+b+", val: "+c);return this.prefs_[e](b,c)};
a.getPref=function(b,c){var d=this.prefs_.getPrefType(b);if(d==Ci.nsIPrefBranch.PREF_INVALID)return c;if(d==Ci.nsIPrefBranch.PREF_STRING&&!this.noUnicode_)return this.getUnicodePref(b,c);var e=G_Preferences$getterMap_[d];if(!e)throw Error("Pref datatype {"+d+"} not supported, key: "+b);try{return this.prefs_[e](b)}catch(f){return c}};
a.setUnicodePref=function(b,c){var d=Cc["@mozilla.org/supports-string;1"].createInstance(Ci.nsISupportsString);d.data=c;return this.prefs_.setComplexValue(b,Ci.nsISupportsString,d)};a.getUnicodePref=function(b,c){try{return this.prefs_.getComplexValue(b,Ci.nsISupportsString).data}catch(d){return c}};a.setBoolPref=function(b,c){return this.setPref(b,c)};a.getBoolPref=function(b){return this.prefs_.getBoolPref(b)};a.clearPref=function(b){try{this.prefs_.clearUserPref(b)}catch(c){}};
a.addObserver=function(b,c){var d=new G_PreferenceObserver(c);this.observers_[b]||(this.observers_[b]=new G_ObjectSafeMap);this.observers_[b].insert(c,d);this.prefs_.addObserver(b,d,false)};a.removeObserver=function(b,c){var d=this.observers_[b].find(c);this.prefs_.removeObserver(b,d);this.observers_[b].erase(c)};var G_Preferences$savePrefFile=function(){var b=Cc["@mozilla.org/preferences;1"].getService(Ci.nsIPrefService);try{b.savePrefFile(null)}catch(c){}};
function G_PreferenceObserver(b){this.debugZone="prefobserver";this.callback_=b}G_PreferenceObserver.prototype.observe=function(b,c,d){this.callback_(d)};G_PreferenceObserver.prototype.QueryInterface=function(b){if(b.equals(Ci.nsISupports)||b.equals(Ci.nsIObserver)||b.equals(Ci.nsISupportsWeakReference))return this;throw Components.results.NS_ERROR_NO_INTERFACE;};function G_DebugZone(){}G_DebugZone.prototype.error=function(){};function G_DebugService(){}G_DebugService.prototype.QueryInterface=function(b){if(b.equals(Ci.nsISupports)||b.equals(Ci.nsITimerCallback))return this;throw Components.results.NS_ERROR_NO_INTERFACE;};
G_DebugService.prototype.notify=function(){if(this.activeSinceLastTimestamp_){this.dump(G_File.LINE_END_CHAR+"=========== Date: "+(new Date).toLocaleString()+" ============"+G_File.LINE_END_CHAR+G_File.LINE_END_CHAR);this.activeSinceLastTimestamp_=false}};G_DebugService.prototype.dump=function(){};G_DebugService.prototype.observe=function(){};function G_Loggifier(){}G_Loggifier.prototype.mark_=function(){};new G_DebugService;var G_File={},G_File$getSpecialFile=function(b,c){var d=Cc["@mozilla.org/file/directory_service;1"].getService(Ci.nsIProperties).get(b,Ci.nsILocalFile);c&&d.append(c);return d},G_File$fromFileURI=function(b){if(b.indexOf("file://")!=0)throw Error("File path must be a file:// URL");var c=Cc["@mozilla.org/network/protocol;1?name=file"].getService(Ci.nsIFileProtocolHandler);return c.getFileFromURLSpec(b)};
G_File.__defineGetter__("LINE_END_CHAR",function(){var b;b="@mozilla.org/xre/app-info;1"in Cc?Cc["@mozilla.org/xre/app-info;1"].getService(Ci.nsIXULRuntime).OS=="WINNT"?"\r\n":"\n":Cc["@mozilla.org/network/protocol;1?name=http"].getService(Ci.nsIHttpProtocolHandler).platform.toLowerCase().indexOf("win")==0?"\r\n":"\n";G_File.__defineGetter__("LINE_END_CHAR",function(){return b});return b});function G_FileReader(b){this.file_=typeof b=="string"?G_File$fromFileURI(b):b}
G_FileReader.prototype.read=function(b){if(!this.stream_){var c=Cc["@mozilla.org/network/file-input-stream;1"].createInstance(Ci.nsIFileInputStream);c.init(this.file_,1,292,0);this.stream_=Cc["@mozilla.org/scriptableinputstream;1"].createInstance(Ci.nsIScriptableInputStream);this.stream_.init(c)}if(typeof b=="undefined")b=this.stream_.available();return this.stream_.read(b)};G_FileReader.prototype.close=function(){if(this.stream_){this.stream_.close();this.stream_=null}};
function G_FileWriter(b,c){this.file_=typeof b=="string"?G_File$fromFileURI(b):b;this.append_=!!c}var G_FileWriter$writeAll=function(b,c,d){b=new G_FileWriter(b,d);try{return b.write(c)}finally{b.close();return 0}};G_FileWriter.prototype.write=function(b){if(!this.stream_){this.stream_=Cc["@mozilla.org/network/file-output-stream;1"].createInstance(Ci.nsIFileOutputStream);var c=10|(this.append_?16:32);this.stream_.init(this.file_,c,-1,0)}return this.stream_.write(b,b.length)};
G_FileWriter.prototype.close=function(){if(this.stream_){this.stream_.close();this.stream_=null}};function G_ObjectSafeMap(b){this.debugZone="objectsafemap";this.name_=b?b:"noname";this.keys_=[];this.values_=[]}a=G_ObjectSafeMap.prototype;a.indexOfKey_=function(b){for(var c=0;c<this.keys_.length;c++)if(this.keys_[c]===b)return c;return-1};
a.insert=function(b,c){if(b===null)throw Error("Can't use null as a key");if(c===undefined)throw Error("Can't store undefined values in this map");var d=this.indexOfKey_(b);if(d==-1){this.keys_.push(b);this.values_.push(c)}else{this.keys_[d]=b;this.values_[d]=c}};a.erase=function(b){b=this.indexOfKey_(b);var c=b!=-1;if(c){this.keys_.splice(b,1);this.values_.splice(b,1)}return c};a.find=function(b){b=this.indexOfKey_(b);return b==-1?undefined:this.values_[b]};
a.replace=function(b){this.keys_=[];this.values_=[];for(var c=0;c<b.keys_.length;c++){this.keys_.push(b.keys_[c]);this.values_.push(b.values_[c])}};a.forEach=function(b){if(typeof b!="function")throw Error("argument to forEach is not a function, it's a(n) "+typeof b);for(var c=0;c<this.keys_.length;c++)b(this.keys_[c],this.values_[c])};a.size=function(){return this.keys_.length};function BindToObject(b){var c=Array.prototype.splice.call(arguments,1,arguments.length);return Function.prototype.bind.apply(b,c)};function G_Alarm(b,c,d,e){this.debugZone="alarm";this.callback_=b;this.repeating_=!!d;b=Components.classes;var f=Components.interfaces;this.timer_=b["@mozilla.org/timer;1"].createInstance(f.nsITimer);d=d?this.timer_.TYPE_REPEATING_SLACK:this.timer_.TYPE_ONE_SHOT;this.maxTimes_=e?e:null;this.nTimes_=0;c=Math.max(c,0);c=Math.min(c,G_Alarm$MAX_DELAY_MILLISEC);this.timer_.initWithCallback(this,c,d)}var G_Alarm$MAX_DELAY_MILLISEC=Math.pow(2,32)-1;
G_Alarm.prototype.cancel=function(){if(this.timer_){this.timer_.cancel();this.callback_=this.timer_=null}};G_Alarm.prototype.notify=function(){var b=this.callback_();this.nTimes_++;if(this.repeating_&&typeof this.maxTimes_=="number"&&this.nTimes_>=this.maxTimes_)this.cancel();else this.repeating_||this.cancel();return b};
G_Alarm.prototype.QueryInterface=function(b){if(b.equals(Components.interfaces.nsISupports)||b.equals(Components.interfaces.nsIObserver)||b.equals(Components.interfaces.nsITimerCallback))return this;throw Components.results.NS_ERROR_NO_INTERFACE;};function G_ConditionalAlarm(b,c,d,e){G_Alarm.call(this,b,c,d,e);this.debugZone="conditionalalarm"}G_ConditionalAlarm.inherits(G_Alarm);G_ConditionalAlarm.prototype.notify=function(b){b=G_Alarm.prototype.notify.call(this,b);this.repeating_&&b&&this.cancel()};function G_ObserverWrapper(b,c){this.debugZone="observer";this.topic_=b;this.observeFunction_=c}G_ObserverWrapper.prototype.QueryInterface=function(b){if(b.equals(Ci.nsISupports)||b.equals(Ci.nsIObserver))return this;throw Components.results.NS_ERROR_NO_INTERFACE;};G_ObserverWrapper.prototype.observe=function(b,c,d){c==this.topic_&&this.observeFunction_(b,c,d)};
function G_ObserverServiceObserver(b,c,d){this.debugZone="observerserviceobserver";this.topic_=b;this.observeFunction_=c;this.onlyOnce_=!!d;this.observer_=new G_ObserverWrapper(this.topic_,BindToObject(this.observe_,this));this.observerService_=Cc["@mozilla.org/observer-service;1"].getService(Ci.nsIObserverService);this.observerService_.addObserver(this.observer_,this.topic_,false)}
G_ObserverServiceObserver.prototype.unregister=function(){this.observerService_.removeObserver(this.observer_,this.topic_);this.observerService_=null};G_ObserverServiceObserver.prototype.observe_=function(b,c,d){this.observeFunction_(b,c,d);this.onlyOnce_&&this.unregister()};function GTM_Config(b){this.initialized_=false;this.file_=b;this.configString_="";this.config_=GTM_Config$defaultConfig_}var GTM_Config$defaultConfig_={collectors:{},eventLimit:1E8,uploadIntervalSec:300};a=GTM_Config.prototype;a.init_=function(){if(!this.initialized_){this.initialized_=true;if(this.file_.exists()){var b;a:{var c=new G_FileReader(this.file_);try{b=c.read();break a}finally{c.close()}b=void 0}if(c=GTM_Config$parseToObject_(b)){this.config_=c;this.configString_=b}}}};
a.isCollectorEnabled=function(b){return b in this.config_.collectors};a.startCollectors=function(){this.init_();for(var b in this.config_.collectors){var c=GTM_Config$getCollector_(b);if(c){c.onAttach();c.onNewLog()}}};a.stopCollectors=function(){for(var b in this.config_.collectors){var c=GTM_Config$getCollector_(b);c&&c.onDetach()}};a.clear=function(){this.stopCollectors();this.file_.exists()&&this.file_.remove(false);this.configString_="";this.config_=GTM_Config$defaultConfig_};
var GTM_Config$getCollector_=function(b){return(b=Cc["@google.com/toolbar/metrics2/collector;1?name="+b])?b.getService(Ci.nsIMetricsCollector2):null};GTM_Config.prototype.load=function(b){this.init_();if(!(this.configString_==b&&this.file_.exists())){var c=GTM_Config$parseToObject_(b);if(c){this.stopCollectors();this.config_=c;this.configString_=b;G_FileWriter$writeAll(this.file_,b);this.startCollectors()}}};
var GTM_Config$parseToObject_=function(b){b=Cc["@mozilla.org/xmlextras/domparser;1"].createInstance(Ci.nsIDOMParser).parseFromString(b,"application/xml");var c=b.documentElement;if(c.namespaceURI!="http://www.mozilla.org/metrics"||c.localName!="response")return null;c=function(i){return i=="gtm"?"http://www.mozilla.org/metrics":null};var d={};d.collectors={};for(var e,f=b.evaluate("//gtm:config/gtm:collectors/gtm:collector",b,c,Ci.nsIDOMXPathResult.ANY_TYPE,null);e=f.iterateNext();)if(e.localName==
"collector")if(e=e.getAttribute("type"))d.collectors[e]=true;f=b.evaluate("//gtm:config/gtm:limit",b,c,Ci.nsIDOMXPathResult.ANY_TYPE,null);d.eventLimit=(e=f.iterateNext())?parseInt(e.getAttribute("events"),10):GTM_Config$defaultConfig_.eventLimit;f=b.evaluate("//gtm:config/gtm:upload",b,c,Ci.nsIDOMXPathResult.ANY_TYPE,null);if(e=f.iterateNext())d.uploadIntervalSec=parseInt(e.getAttribute("interval"),10);if(!d.uploadIntervalSec)return null;return d};
GTM_Config.prototype.isEventEnabled=function(b,c){this.init_();return b=="http://www.mozilla.org/metrics"&&!!this.config_.collectors[c]};GTM_Config.prototype.getEventLimit=function(){this.init_();return this.config_.eventLimit};GTM_Config.prototype.getUploadIntervalSec=function(){this.init_();return this.config_.uploadIntervalSec};function GTM_EventItem(b,c){this.itemNamespace=b;this.itemName=c;this.properties=null;this.children_=[]}GTM_EventItem.prototype.QueryInterface=function(b){if(b.equals(Ci.nsIMetricsEventItem2)||b.equals(Ci.nsISupports))return this;throw Cr.NS_ERROR_NO_INTERFACE;};GTM_EventItem.prototype.QueryInterface=GTM_EventItem.prototype.QueryInterface;GTM_EventItem.prototype.itemNamespace="";GTM_EventItem.prototype.itemNamespace=GTM_EventItem.prototype.itemNamespace;GTM_EventItem.prototype.itemName="";
GTM_EventItem.prototype.itemName=GTM_EventItem.prototype.itemName;GTM_EventItem.prototype.properties=null;GTM_EventItem.prototype.properties=GTM_EventItem.prototype.properties;GTM_EventItem.prototype.childAt=function(b){return this.children_[b]};GTM_EventItem.prototype.childAt=GTM_EventItem.prototype.childAt;GTM_EventItem.prototype.indexOf=function(b){return this.children_.indexOf(b)};GTM_EventItem.prototype.indexOf=GTM_EventItem.prototype.indexOf;GTM_EventItem.prototype.appendChild=function(b){this.children_.push(b)};
GTM_EventItem.prototype.appendChild=GTM_EventItem.prototype.appendChild;GTM_EventItem.prototype.insertChildAt=function(b,c){this.children_.splice(c,0,b)};GTM_EventItem.prototype.insertChildAt=GTM_EventItem.prototype.insertChildAt;GTM_EventItem.prototype.removeChildAt=function(b){this.children_.splice(b,1)};GTM_EventItem.prototype.removeChildAt=GTM_EventItem.prototype.removeChildAt;GTM_EventItem.prototype.removeChildAt=GTM_EventItem.prototype.removeChildAt;
GTM_EventItem.prototype.clearChildren=function(){for(;this.children_.pop(););};GTM_EventItem.prototype.clearChildren=GTM_EventItem.prototype.clearChildren;GTM_EventItem.prototype.__defineGetter__("childCount",function(){return this.children_.length});function GTM_LogXml(b,c){this.initialized_=false;this.sessionID_=b;this.root_=this.document_=null;this.file_=c}a=GTM_LogXml.prototype;a.init_=function(){if(!this.initialized_){this.initialized_=true;this.document_=Cc["@mozilla.org/xml/xml-document;1"].createInstance(Ci.nsIDOMDocument);this.startChunk_();this.file_&&!this.file_.exists()&&this.file_.create(this.file_.NORMAL_FILE_TYPE,384)}};a.startChunk_=function(){this.root_=this.document_.createElementNS("http://www.mozilla.org/metrics","log")};
a.logEvent=function(b){this.init_();if(!b)throw Error("Null event");b=this.buildDomElement_(b);b.setAttribute("time",String(Math.floor(Date.now()/1E3)));b.setAttribute("session",this.sessionID_);this.root_.appendChild(b)};
a.buildDomElement_=function(b){var c=this.document_.createElementNS(b.itemNamespace,b.itemName);if(b.properties)for(var d=b.properties.enumerator;d.hasMoreElements();){var e=d.getNext().QueryInterface(Ci.nsIProperty);e&&e.name&&c.setAttribute(e.name,String(e.value))}for(d=0;d<b.childCount;++d){e=this.buildDomElement_(b.childAt(d));c.appendChild(e)}return c};
a.getChunkXmlString=function(){this.init_();var b=Cc["@mozilla.org/xmlextras/xmlserializer;1"].createInstance(Ci.nsIDOMSerializer).serializeToString(this.root_);return b.replace(/^[^>]+>|<[^<]+$/g,"")};a.flushChunk=function(){this.init_();var b=this.getChunkXmlString();G_FileWriter$writeAll(this.file_,b,true);this.startChunk_()};
a.openFlushedXmlStream=function(){this.init_();var b;b=new G_Preferences("metrics.");var c=b.getPref("client-id","");if(!c){c=[];var d=Date.now(),e;for(e=0;e<8;++e){c.push(d%256);d=Math.floor(d/256)}for(e=0;e<32;++e)c.push(Math.floor(Math.random()*256));d=Cc["@mozilla.org/security/hash;1"].createInstance(Ci.nsICryptoHash);d.init(d.MD5);d.update(c,c.length);c=c=d.finish(true);b.setPref("client-id",c);G_Preferences$savePrefFile()}b=c;c='<?xml version="1.0"?>\n<log xmlns="http://www.mozilla.org/metrics" version="2" clientid="'+
b+'">\n';d="</log>";b=Cc["@mozilla.org/io/string-input-stream;1"].createInstance(Ci.nsIStringInputStream);b.setData(c,c.length);c=Cc["@mozilla.org/io/string-input-stream;1"].createInstance(Ci.nsIStringInputStream);c.setData(d,d.length);d=Cc["@mozilla.org/network/file-input-stream;1"].createInstance(Ci.nsIFileInputStream);d.init(this.file_,-1,-1,0);e=Cc["@mozilla.org/io/multiplex-input-stream;1"].createInstance(Ci.nsIMultiplexInputStream);e.appendStream(b);e.appendStream(d);e.appendStream(c);return e};
a.deleteFlushedXml=function(){if(this.file_&&this.file_.exists()){this.file_.remove(false);this.file_.create(this.file_.NORMAL_FILE_TYPE,384)}};a.clear=function(){this.init_();this.file_.exists()&&this.file_.remove(false);this.startChunk_()};a.setSessionID=function(b){this.sessionID_=b};function GTM_Service(){this.initialized_=false;this.eventCount_=this.suspendCount_=0;this.upload_=this.logger_=this.configFile_=this.config_=this.prefs_=null;this.uploadRetryCount_=0}var GTM_Service$instance_;G_JSModule$getInstance().registerObject("{6174fe7b-320f-4606-a855-a8cdfdf7ba80}","@google.com/toolbar/metrics2/service;1","Google Toolbar Metrics Service",GTM_Service$instance_||(GTM_Service$instance_=new GTM_Service),["app-startup"]);
GTM_Service.prototype.QueryInterface=function(b){if(b.equals(Ci.nsIMetricsService2)||b.equals(Ci.nsIObserver)||b.equals(Ci.nsISupports))return this;throw Cr.NS_ERROR_NO_INTERFACE;};goog$exportPath_("GTM_Service.prototype.QueryInterface",GTM_Service.prototype.QueryInterface,void 0);GTM_Service.prototype.observe=function(b,c){"app-startup"==c&&new G_ObserverServiceObserver("profile-after-change",BindToObject(this.init_,this))};
goog$exportPath_("GTM_Service.prototype.observe",GTM_Service.prototype.observe,void 0);a=GTM_Service.prototype;
a.init_=function(){if(!this.initialized_){this.initialized_=true;this.prefs_=new G_Preferences("metrics.");this.prefs_.addObserver("upload.enable",BindToObject(this.onEnablePrefChange_,this));new G_ObserverServiceObserver("quit-application",BindToObject(this.stopCollection_,this));this.eventCount_=this.prefs_.getPref("event-count",0);this.logger_=new GTM_LogXml(this.prefs_.getPref("last-session-id",-1),G_File$getSpecialFile("ProfD","gtb-metrics.xml"));this.upload_=new GTM_Upload;this.configFile_=
G_File$getSpecialFile("ProfD","gtb-metrics-config.xml");this.config_=new GTM_Config(this.configFile_);new G_Alarm(BindToObject(this.onEnablePrefChange_,this),0)}};a.onEnablePrefChange_=function(){var b=this.prefs_.getPref("upload.enable",false);b?this.startCollection_():this.clearCollection_()};
a.startCollection_=function(){var b=this.prefs_.getPref("last-session-id",-1)+1;this.prefs_.setPref("last-session-id",b);this.logger_.setSessionID(b);this.config_.startCollectors();this.configFile_.exists()?this.rescheduleUpload_():this.upload();G_Preferences$savePrefFile()};a.clearCollection_=function(){this.config_.clear();this.logger_.clear();this.prefs_.clearPref("event-count");this.prefs_.clearPref("upload.next-time");this.prefs_.clearPref("upload.next-ping");G_Preferences$savePrefFile()};
a.stopCollection_=function(){this.config_.stopCollectors();this.flush()};a.createEventItem=function(b,c){return new GTM_EventItem(b,c)};goog$exportPath_("GTM_Service.prototype.createEventItem",GTM_Service.prototype.createEventItem,void 0);
GTM_Service.prototype.logEvent=function(b){if(!b)throw Error("Null event");if(!(this.suspendCount_>0||this.eventCount_>=this.config_.getEventLimit()||!this.config_.isEventEnabled(b.itemNamespace,b.itemName))){this.logger_.logEvent(b);++this.eventCount_;this.eventCount_%64==0&&this.flush()}};goog$exportPath_("GTM_Service.prototype.logEvent",GTM_Service.prototype.logEvent,void 0);GTM_Service.prototype.logSimpleEvent=function(b,c,d){b=this.createEventItem(b,c);b.properties=d;return this.logEvent(b)};
goog$exportPath_("GTM_Service.prototype.logSimpleEvent",GTM_Service.prototype.logSimpleEvent,void 0);GTM_Service.prototype.flush=function(){if(!this.upload_.isUploading()){this.logger_.flushChunk();this.prefs_.setPref("event-count",this.eventCount_);G_Preferences$savePrefFile()}};goog$exportPath_("GTM_Service.prototype.flush",GTM_Service.prototype.flush,void 0);
GTM_Service.prototype.upload=function(){if(!this.upload_.isUploading()){var b=this.configFile_.exists();if(b&&0==this.eventCount_&&this.prefs_.getPref("upload.next-ping",0)*1E3>Date.now())this.rescheduleUpload_();else{this.flush();this.upload_.upload(this.logger_.openFlushedXmlStream(),BindToObject(this.onFinishUpload,this))}}};goog$exportPath_("GTM_Service.prototype.upload",GTM_Service.prototype.upload,void 0);a=GTM_Service.prototype;
a.rescheduleUpload_=function(){var b=this.config_.getUploadIntervalSec()*1E3,c=this.prefs_.getPref("upload.next-time",null);if(c!=null)b=Math.max(0,c*1E3-Date.now());new G_Alarm(BindToObject(this.upload,this),b)};
a.onFinishUpload=function(b,c,d){b&&this.config_.load(d);c<500&&this.removeLoggedData_();if(b=b&&200==c){this.uploadRetryCount_=0;this.prefs_.clearPref("upload.next-time");this.prefs_.setPref("upload.next-ping",this.getRandomUploadTimeSec_())}else if(++this.uploadRetryCount_>=3){this.uploadRetryCount_=0;this.removeLoggedData_();this.prefs_.setPref("upload.next-time",this.getRandomUploadTimeSec_())}this.rescheduleUpload_()};
a.removeLoggedData_=function(){this.logger_.deleteFlushedXml();var b=this.prefs_.getPref("event-count",0);this.prefs_.setPref("event-count",0);this.eventCount_-=b};a.getRandomUploadTimeSec_=function(){var b=3600;return Math.floor(Date.now()/1E3+(12+Math.random()*24)*b)};a.isCollectorEnabled=function(b){return this.config_.isCollectorEnabled(b)};goog$exportPath_("GTM_Service.prototype.isCollectorEnabled",GTM_Service.prototype.isCollectorEnabled,void 0);GTM_Service.prototype.suspend=function(){++this.suspendCount_};
goog$exportPath_("GTM_Service.prototype.suspend",GTM_Service.prototype.suspend,void 0);GTM_Service.prototype.resume=function(){this.suspendCount_>0&&--this.suspendCount_};goog$exportPath_("GTM_Service.prototype.resume",GTM_Service.prototype.resume,void 0);GTM_Service.prototype.getWindowID=function(b){return goog$getHashCode(b)};goog$exportPath_("GTM_Service.prototype.getWindowID",GTM_Service.prototype.getWindowID,void 0);function GTM_Upload(){this.uploading_=false;this.callback_=null;this.responseString_="";this.observer_=this.responseOStream_=this.responseFile_=null}a=GTM_Upload.prototype;a.QueryInterface=function(b){if(b.equals(Ci.nsIStreamListener)||b.equals(Ci.nsISupports))return this;throw Cr.NS_ERROR_NO_INTERFACE;};a.isUploading=function(){return this.uploading_};
a.upload=function(b,c){var d=new G_Preferences("metrics.");if(d.getPref("upload.enable",false)){var e=d.getPref("upload.uri","");if(e){try{d="application/vnd.mozilla.metrics.bz2";var f=this.compressStream_(b)}catch(i){d="application/vnd.mozilla.metrics";f=b}var h=Cc["@mozilla.org/network/io-service;1"].getService(Ci.nsIIOService);e=h.newChannel(e,null,null);this.mark_(e);h=e.QueryInterface(Ci.nsIUploadChannel);h.setUploadStream(f,d,-1);f=e.QueryInterface(Ci.nsIHttpChannel);f.requestMethod="POST";
e.asyncOpen(this,null);this.uploading_=true;this.callback_=c}}};
a.compressStream_=function(b){var c=G_File$getSpecialFile("ProfD","gtb-metrics.xml.bz2"),d=Cc["@mozilla.org/network/file-output-stream;1"].createInstance(Ci.nsIFileOutputStream);d.init(c,42,384,0);Cc["@google.com/toolbar/compress-bz2;1"].createInstance(Ci.gtbIStreamCompressor).compress(b,d);d.close();b.close();b=Cc["@mozilla.org/network/file-input-stream;1"].createInstance(Ci.nsIFileInputStream);b.init(c,-1,-1,b.DELETE_ON_CLOSE);c=Cc["@mozilla.org/network/buffered-input-stream;1"].createInstance(Ci.nsIBufferedInputStream);c.init(b,
4096);return c};a.onStartRequest=function(){this.responseString_=""};a.onDataAvailable=function(b,c,d,e,f){b=Cc["@mozilla.org/binaryinputstream;1"].createInstance(Ci.nsIBinaryInputStream);b.setInputStream(d);this.responseString_+=b.readBytes(f);b.close()};a.onStopRequest=function(b,c,d){b=b.QueryInterface(Ci.nsIHttpChannel).responseStatus;this.uploading_=false;if(this.callback_){this.callback_(d==0,b,this.responseString_);this.callback_=null}};
a.mark_=function(b){b=b.QueryInterface(Ci.nsIWritablePropertyBag);b.setProperty("gtm-upload-request",true);if(!this.observer_)this.observer_=new G_ObserverServiceObserver("http-on-modify-request",BindToObject(this.stripCookiesFromUploadRequest_,this))};
a.stripCookiesFromUploadRequest_=function(b){var c=b.QueryInterface(Ci.nsIPropertyBag);if(c)if(c.getProperty("gtm-upload-request"))if(b=b.QueryInterface(Ci.nsIHttpChannel)){b.setRequestHeader("Cookie","",false);this.observer_.unregister();this.observer_=null}};var goog$debug$Error=function(b){this.stack=Error().stack||"";if(b)this.message=String(b)};goog$inherits(goog$debug$Error,Error);goog$debug$Error.prototype.name="CustomError";var goog$string$subs=function(b){for(var c=1;c<arguments.length;c++){var d=String(arguments[c]).replace(/\$/g,"$$$$");b=b.replace(/\%s/,d)}return b};var goog$asserts$AssertionError=function(b,c){c.unshift(b);goog$debug$Error.call(this,goog$string$subs.apply(null,c));c.shift();this.messagePattern=b};goog$inherits(goog$asserts$AssertionError,goog$debug$Error);goog$asserts$AssertionError.prototype.name="AssertionError";function GTM_HistogramCollector(){this.lastConnect_={};this.histograms={};this.histograms.searchPageLoad=new GTM_ExponentialHistogram(0,6E4,20);this.histograms.searchRecency=new GTM_ExponentialHistogram(0,9E5,20);this.histograms.hoverDnsResolutionDone=new GTM_ExponentialHistogram(0,3E4,20);this.histograms.hoverDnsSuccess=new GTM_ExponentialHistogram(0,3E4,20);this.histograms.hoverDnsEarlyNavigation=new GTM_ExponentialHistogram(0,3E4,20);this.histograms.hoverDnsUnnecessary=new GTM_ExponentialHistogram(0,
3E4,20);this.histograms.dnsResourceTimeSaved=new GTM_ExponentialHistogram(0,3E4,20);this.histograms.dnsResourceUnnecessary=new GTM_ExponentialHistogram(0,3E4,20);this.histograms.dnsResourceFailed=new GTM_ExponentialHistogram(0,3E4,20);this.histograms.dnsResourceCount=new GTM_ExponentialHistogram(0,50,20);this.histograms.dnsTotalResources=new GTM_ExponentialHistogram(0,5E4,50)}GTM_registerMetricsCollector("{FC9F3232-4B92-11DE-80A5-35FF55D89593}","histogram",new GTM_HistogramCollector);
GTM_HistogramCollector.prototype.debugZone="histogram-collector";GTM_HistogramCollector.prototype.QueryInterface=function(b){if(b.equals(Ci.nsISupports)||b.equals(Ci.nsIObserver)||b.equals(Ci.nsIMetricsCollector2))return this;throw Cr.NS_ERROR_NO_INTERFACE;};goog$exportPath_("GTM_HistogramCollector.prototype.QueryInterface",GTM_HistogramCollector.prototype.QueryInterface,void 0);GTM_HistogramCollector.prototype.observe=function(b,c,d){GTM_HistogramCollector$handlers[c].call(this,b,d)};
goog$exportPath_("GTM_HistogramCollector.prototype.observe",GTM_HistogramCollector.prototype.observe,void 0);GTM_HistogramCollector.prototype.onAttach=function(){var b=Cc["@mozilla.org/observer-service;1"].getService(Ci.nsIObserverService);for(var c in GTM_HistogramCollector$handlers)b.addObserver(this,c,false);this.regularFlushTimer_=new G_Alarm(BindToObject(this.flushLog,this),36E5,true)};goog$exportPath_("GTM_HistogramCollector.prototype.onAttach",GTM_HistogramCollector.prototype.onAttach,void 0);
GTM_HistogramCollector.prototype.onDetach=function(){this.regularFlushTimer_.cancel();this.flushLog();var b=Cc["@mozilla.org/observer-service;1"].getService(Ci.nsIObserverService);for(var c in GTM_HistogramCollector$handlers)b.removeObserver(this,c,false)};goog$exportPath_("GTM_HistogramCollector.prototype.onDetach",GTM_HistogramCollector.prototype.onDetach,void 0);GTM_HistogramCollector.prototype.onNewLog=function(){};
goog$exportPath_("GTM_HistogramCollector.prototype.onNewLog",GTM_HistogramCollector.prototype.onNewLog,void 0);a=GTM_HistogramCollector.prototype;a.onSearchPreconnect_=function(b,c){var d=c;this.lastConnect_[d]=Date.now()};
a.onSearchResultLoaded_=function(b){b=b.QueryInterface(Ci.nsIDOMDocument);var c=b.defaultView;b=c.location.host;c=(c.wrappedJSObject||c).gtbExternal;c=c.pageT();var d=b in this.lastConnect_?Date.now()-this.lastConnect_[b]:9E5;this.lastConnect_[b]=Date.now();this.histograms.searchPageLoad.add(c);this.histograms.searchRecency.add(d)};a.onHoverDnsResolutionDone_=function(b,c){this.histograms.hoverDnsResolutionDone.add(parseInt(c,10))};
a.onHoverDnsSuccess_=function(b,c){this.histograms.hoverDnsSuccess.add(parseInt(c,10))};a.onHoverDnsEarlyNavigation_=function(b,c){this.histograms.hoverDnsEarlyNavigation.add(parseInt(c,10))};a.onHoverDnsUnnecessary_=function(b,c){this.histograms.hoverDnsUnnecessary.add(parseInt(c,10))};a.onDnsResourceTimeSaved_=function(b,c){this.histograms.dnsResourceTimeSaved.add(parseInt(c,10))};a.onDnsResourceUnnecessary_=function(b,c){this.histograms.dnsResourceUnnecessary.add(parseInt(c,10))};
a.onDnsResourceFailed_=function(b,c){this.histograms.dnsResourceFailed.add(parseInt(c,10))};a.onDnsResourceCount_=function(b,c){this.histograms.dnsResourceCount.add(parseInt(c,10))};a.onDnsTotalResources_=function(b,c){this.histograms.dnsTotalResources.add(parseInt(c,10))};
var GTM_HistogramCollector$handlers={GTB_SEARCH_PRECONNECT:GTM_HistogramCollector.prototype.onSearchPreconnect_,GTB_SEARCH_LOADED:GTM_HistogramCollector.prototype.onSearchResultLoaded_,GTB_DNS_RESOURCE_TIME_SAVED:GTM_HistogramCollector.prototype.onDnsResourceTimeSaved_,GTB_DNS_RESOURCE_UNNECESSARY:GTM_HistogramCollector.prototype.onDnsResourceUnnecessary_,GTB_DNS_RESOURCE_FAILED:GTM_HistogramCollector.prototype.onDnsResourceFailed_,GTB_DNS_RESOURCE_COUNT:GTM_HistogramCollector.prototype.onDnsResourceCount_,
GTB_DNS_TOTAL_RESOURCES:GTM_HistogramCollector.prototype.onDnsTotalResources_,GTB_HOVER_DNS_RESOLUTION_DONE:GTM_HistogramCollector.prototype.onHoverDnsResolutionDone_,GTB_HOVER_DNS_SUCCESS:GTM_HistogramCollector.prototype.onHoverDnsSuccess_,GTB_HOVER_DNS_EARLY_NAVIGATION:GTM_HistogramCollector.prototype.onHoverDnsEarlyNavigation_,GTB_HOVER_DNS_UNNECESSARY:GTM_HistogramCollector.prototype.onHoverDnsUnnecessary_};
GTM_HistogramCollector.prototype.flushLog=function(){var b=GTM_getMetricsService(),c=0;for(var d in this.histograms){var e=this.histograms[d];c+=e.sum;if(e.sum>0){var f=new GTM_HistogramCollector$LogEventBuilder(b);f.beginElement("histogram");var i=f.getCurrent();f.attrib("name",d);e.record(f);e.clear();f.endElement();b.logEvent(i)}}};var GTM_HistogramCollector$LogEventBuilder=function(b){this.metricsService_=b;this.items_=[];this.props_=[]};
GTM_HistogramCollector$LogEventBuilder.prototype.beginElement=function(b){b=this.metricsService_.createEventItem("http://www.mozilla.org/metrics",b);this.items_.length>0&&this.getCurrent().appendChild(b);this.items_.push(b);this.props_.push(null)};GTM_HistogramCollector$LogEventBuilder.prototype.endElement=function(){var b=this.items_.pop(),c=this.props_.pop();if(c)b.properties=c};
GTM_HistogramCollector$LogEventBuilder.prototype.attrib=function(b,c){var d=this.props_[this.props_.length-1];if(!d){d=GTM_createPropertyBag();this.props_[this.props_.length-1]=d}d.setProperty(b,c)};GTM_HistogramCollector$LogEventBuilder.prototype.getCurrent=function(){return this.items_[this.items_.length-1]};function GTM_ExponentialHistogram(b,c,d){var e;e=c;d=d;for(var f=[b],i=Math.log(e),h=0,j=b;d>=++h;){var g=Math.log(j),k=(i-g)/(d-h);g=g+k;g=Math.floor(Math.exp(g)+0.5);if(g>j)j=g;else++j;if(j>e)break;f.push(j)}f.push(e);this.ranges_=e=f;e=this.ranges_.length-1;d=[];for(f=0;f<e;f++)d[f]=0;this.counts_=e=d;this.sumsquares=this.sum=0;this.min=b;this.max=c}GTM_ExponentialHistogram.prototype.add=function(b){var c=this.bucketIndex_(b);this.counts_[c]++;this.sum+=b;this.sumsquares+=b*b};
GTM_ExponentialHistogram.prototype.bucketIndex_=function(b){for(var c=this.ranges_,d=0,e=c.length-1;e-d>1;){var f=d+e>>1;if(b>=c[f])d=f;else e=f}return d};GTM_ExponentialHistogram.prototype.record=function(b){b.attrib("sum",this.sum);b.attrib("sumsquares",this.sumsquares);for(var c=this.ranges_,d=this.counts_,e=0;e<d.length;e++)if(d[e]!=0){b.beginElement("histogrambucket");b.attrib("min",c[e]);b.attrib("max",c[e+1]);b.attrib("count",d[e]);b.endElement()}};
GTM_ExponentialHistogram.prototype.clear=function(){for(var b=this.sumsquares=this.sum=0;b<this.counts_.length;b++)this.counts_[b]=0};function GTM_UICollector(){this.hasher_=this.service_=null;this.handlers_={};this.winObserver_=null}var GTM_UICollector$instance_;GTM_registerMetricsCollector("{243c7314-ee15-41eb-923e-695a64bbc712}","uielement",GTM_UICollector$instance_||(GTM_UICollector$instance_=new GTM_UICollector));GTM_UICollector.prototype.QueryInterface=function(b){if(b.equals(Ci.nsIMetricsCollector2)||b.equals(Ci.nsISupports))return this;throw Cr.NS_ERROR_NO_INTERFACE;};
goog$exportPath_("GTM_UICollector.prototype.QueryInterface",GTM_UICollector.prototype.QueryInterface,void 0);
GTM_UICollector.prototype.onAttach=function(){this.service_=GTM_getMetricsService();this.hasher_=new GTM_Hasher;this.handlers_.command=BindToObject(this.handleCommand_,this);this.handlers_.TabMove=BindToObject(this.handleTabMove_,this);this.winObserver_=new G_ObserverServiceObserver("domwindowopened",BindToObject(this.addEventListeners_,this));this.forEachWindow_(BindToObject(this.addEventListeners_,this))};goog$exportPath_("GTM_UICollector.prototype.onAttach",GTM_UICollector.prototype.onAttach,void 0);
GTM_UICollector.prototype.onDetach=function(){this.hasher_=this.service_=null;this.winObserver_.unregister();this.winObserver_=null;this.forEachWindow_(BindToObject(this.removeEventListeners_,this))};goog$exportPath_("GTM_UICollector.prototype.onDetach",GTM_UICollector.prototype.onDetach,void 0);GTM_UICollector.prototype.onNewLog=function(){};goog$exportPath_("GTM_UICollector.prototype.onNewLog",GTM_UICollector.prototype.onNewLog,void 0);a=GTM_UICollector.prototype;
a.forEachWindow_=function(b){var c=Cc["@mozilla.org/appshell/window-mediator;1"].getService(Ci.nsIWindowMediator);for(c=c.getEnumerator("");c.hasMoreElements();){var d=c.getNext();b(d)}};a.addEventListeners_=function(b){for(var c in this.handlers_)b.addEventListener(c,this.handlers_[c],true)};a.removeEventListeners_=function(b){for(var c in this.handlers_)b.removeEventListener(c,this.handlers_[c],true)};
a.handleCommand_=function(b){var c=this.createBag_(this.getWindowId_(b),this.getTargetId_(b));if(c){var d=this.getTargetAnonId_(b);d&&c.setProperty("targetanonidhash",this.hasher_.hashString(d));(b=this.getEventKeyId_(b))&&c.setProperty("keyidhash",this.hasher_.hashString(b));this.service_.logSimpleEvent("http://www.mozilla.org/metrics","uielement",c)}};
a.handleTabMove_=function(b){(b=this.createBag_(this.getWindowId_(b),"TabMove_Event"))&&this.service_.logSimpleEvent("http://www.mozilla.org/metrics","uielement",b)};a.createBag_=function(b,c){if(!b||!c)return null;var d=GTM_createPropertyBag();d.setProperty("window",b);d.setProperty("action","command");d.setProperty("targetidhash",this.hasher_.hashString(c));return d};
a.getWindowId_=function(b){return(b=(b=(b=(b=(b=b.target&&b.target.QueryInterface(Ci.nsIDOMNode))&&b.ownerDocument)&&b.QueryInterface(Ci.nsIDOMDocumentView))&&b.defaultView)&&b.QueryInterface(Ci.nsIDOMWindow))&&this.service_&&this.service_.getWindowID(b)};a.getTargetId_=function(b){return(b=b.target&&b.target.QueryInterface(Ci.nsIDOMElement))&&b.getAttribute("id")};
a.getTargetAnonId_=function(b){if(!this.getTargetId_(b))return null;var c=(b=(b=(b=b.QueryInterface(Ci.nsIDOMNSEvent))&&b.originalTarget)&&b.QueryInterface(Ci.nsIDOMElement))&&b.getAttribute("id");return c?null:b&&b.getAttribute("anonid")};
a.getEventKeyId_=function(b){try{var c=b.QueryInterface(Ci.nsIDOMXULCommandEvent)}catch(d){return null}if((b=(b=(b=c&&c.sourceEvent)&&b.target)&&b.QueryInterface(Ci.nsIDOMElement))&&b.namespaceURI=="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"&&b.localName=="key")return b.getAttribute("id");return null};function GTM_BookmarkCounter(){this.liveMarkService_=null;this.separatorCount=this.livemarkCount=this.folderCount=this.itemCount=0}GTM_BookmarkCounter.prototype.init=function(){this.liveMarkService_=Cc["@mozilla.org/browser/livemark-service;2"].getService(Ci.nsILivemarkService)};GTM_BookmarkCounter.prototype.reset=function(){this.itemCount=this.folderCount=this.livemarkCount=this.separatorCount=0};
GTM_BookmarkCounter.prototype.countChildren=function(b,c){var d=Cc["@mozilla.org/browser/nav-history-service;1"].getService(Ci.nsINavHistoryService),e=d.getNewQuery();e.setFolders([b],1);e.onlyBookmarked=true;d=d.executeQuery(e,d.getNewQueryOptions());this.countRecursive_(d.root,c)};
GTM_BookmarkCounter.prototype.countRecursive_=function(b,c){b.QueryInterface(Ci.nsINavHistoryContainerResultNode);b.containerOpen=true;for(var d=0;d<b.childCount;d++){var e=b.getChild(d),f=e.type;if(f==Ci.nsINavHistoryResultNode.RESULT_TYPE_URI)this.itemCount++;else if(f==Ci.nsINavHistoryResultNode.RESULT_TYPE_SEPARATOR)this.separatorCount++;else if(f==Ci.nsINavHistoryResultNode.RESULT_TYPE_FOLDER)if(this.liveMarkService_.isLivemark(e.itemId))this.livemarkCount++;else{this.folderCount++;c&&this.countRecursive_(e,
c)}}};function GTM_ProfileCollector(){this.hasher_=this.service_=null}var GTM_ProfileCollector$instance_;GTM_registerMetricsCollector("{3f4050b8-aa81-40f8-b848-44cefaa7c4ce}","profile",GTM_ProfileCollector$instance_||(GTM_ProfileCollector$instance_=new GTM_ProfileCollector));GTM_ProfileCollector.prototype.QueryInterface=function(b){if(b.equals(Ci.nsIMetricsCollector2)||b.equals(Ci.nsISupports))return this;throw Cr.NS_ERROR_NO_INTERFACE;};
goog$exportPath_("GTM_ProfileCollector.prototype.QueryInterface",GTM_ProfileCollector.prototype.QueryInterface,void 0);GTM_ProfileCollector.prototype.onAttach=function(){this.service_=GTM_getMetricsService();this.hasher_=new GTM_Hasher};goog$exportPath_("GTM_ProfileCollector.prototype.onAttach",GTM_ProfileCollector.prototype.onAttach,void 0);
GTM_ProfileCollector.prototype.onNewLog=function(){var b=this.service_.createEventItem("http://www.mozilla.org/metrics","profile");b.properties=GTM_createPropertyBag();this.logOsCpu_(b);this.logDisplay_(b);this.logInstall_(b);Cc["@mozilla.org/browser/nav-history-service;1"]&&Cc["@mozilla.org/browser/nav-bookmarks-service;1"]&&Cc["@mozilla.org/browser/livemark-service;2"]&&this.logBookmarks_(b);this.logExtensions_(b);this.logPlugins_(b);this.service_.logEvent(b)};
goog$exportPath_("GTM_ProfileCollector.prototype.onNewLog",GTM_ProfileCollector.prototype.onNewLog,void 0);GTM_ProfileCollector.prototype.onDetach=function(){this.hasher_=this.service_=null};goog$exportPath_("GTM_ProfileCollector.prototype.onDetach",GTM_ProfileCollector.prototype.onDetach,void 0);a=GTM_ProfileCollector.prototype;
a.logOsCpu_=function(b){var c=Cc["@mozilla.org/system-info;1"].getService(Ci.nsIPropertyBag),d=this.service_.createEventItem("http://www.mozilla.org/metrics","os");d.properties=GTM_createPropertyBag();d.properties.setProperty("name",c.getProperty("name"));d.properties.setProperty("version",c.getProperty("version"));b.appendChild(d);d=this.service_.createEventItem("http://www.mozilla.org/metrics","cpu");d.properties=GTM_createPropertyBag();d.properties.setProperty("arch",c.getProperty("arch"));b.appendChild(d)};
a.logDisplay_=function(b){var c=this.service_.createEventItem("http://www.mozilla.org/metrics","display");c.properties=GTM_createPropertyBag();var d=Cc["@mozilla.org/gfx/screenmanager;1"].getService(Ci.nsIScreenManager);c.properties.setProperty("screens",d.numberOfScreens);d=d.primaryScreen;var e={},f={},i={},h={};d.GetRect(e,f,i,h);c.properties.setProperty("xsize",i.value);c.properties.setProperty("ysize",h.value);b.appendChild(c)};
a.logInstall_=function(b){var c=this.service_.createEventItem("http://www.mozilla.org/metrics","install");c.properties=GTM_createPropertyBag();var d=Cc["@mozilla.org/xre/app-info;1"].getService(Ci.nsIXULAppInfo);c.properties.setProperty("buildid",d.appBuildID);var e=Cc["@mozilla.org/extensions/manager;1"].getService(Ci.nsIExtensionManager);e=e.getItemForID("{3112ca9c-de6d-4884-a869-9855de68056c}");c.properties.setProperty("extversion",e.version);c.properties.setProperty("appversion",d.version);d=
Cc["@mozilla.org/intl/nslocaleservice;1"].getService(Ci.nsILocaleService);d=d.getApplicationLocale();d=d.getCategory("NSILOCALE_CTYPE");c.properties.setProperty("locale",d);if((d=G_File$getSpecialFile("PrfDef","channel-prefs.js"))&&d.exists()){d=d.lastModifiedTime/1E3;e=86400;c.properties.setProperty("installdate",Math.floor(d/e)*e)}c.properties.setProperty("default",1);b.appendChild(c)};
a.logBookmarks_=function(b){var c=this.service_.createEventItem("http://www.mozilla.org/metrics","bookmarks"),d=Cc["@mozilla.org/browser/nav-bookmarks-service;1"].getService(Ci.nsINavBookmarksService),e=new GTM_BookmarkCounter;e.init();this.logBookmarkLocation_(c,"full-tree",e,d.placesRoot,true);this.logBookmarkLocation_(c,"root",e,d.bookmarksMenuFolder,false);this.logBookmarkLocation_(c,"toolbar",e,d.toolbarFolder,false);b.appendChild(c)};
a.logExtensions_=function(b){var c=this.service_.createEventItem("http://www.mozilla.org/metrics","extensions"),d=Cc["@mozilla.org/extensions/manager;1"].getService(Ci.nsIExtensionManager),e=Cc["@mozilla.org/rdf/rdf-service;1"].getService(Ci.nsIRDFService),f=d.getItemList(Ci.nsIUpdateItem.TYPE_EXTENSION,{});d=d.datasource;for(var i=e.GetResource("http://www.mozilla.org/2004/em-rdf#disabled"),h=e.GetResource("http://www.mozilla.org/2004/em-rdf#isDisabled"),j=0;j<f.length;j++){var g=f[j],k=this.service_.createEventItem("http://www.mozilla.org/metrics",
"extension"),l=GTM_createPropertyBag();l.setProperty("extensionid",this.hasher_.hashString(g.id));g.version&&l.setProperty("version",g.version);g=e.GetResource("urn:mozilla:item:"+g.id);var m=d.GetTarget(g,i,true);m||(m=d.GetTarget(g,h,true));if(m)if(g=m.QueryInterface(Ci.nsIRDFLiteral)){g=g.Value;g=="true"&&l.setProperty("disabled",true)}k.properties=l;c.appendChild(k)}b.appendChild(c)};
a.logPlugins_=function(b){var c=this.service_.createEventItem("http://www.mozilla.org/metrics","plugins");if(Ci.nsIPluginHost){var d=Cc["@mozilla.org/plugin/host;1"].getService(Ci.nsIPluginHost);d=d.getPluginTags({});for(var e=0;e<d.length;e++){var f=d[e],i=this.service_.createEventItem("http://www.mozilla.org/metrics","plugin"),h=GTM_createPropertyBag();h.setProperty("name",this.hasher_.hashString(f.name));h.setProperty("filename",this.hasher_.hashString(f.filename));i.properties=h;c.appendChild(i)}}b.appendChild(c)};
a.logBookmarkLocation_=function(b,c,d,e,f){d.reset();d.countChildren(e,f);e=GTM_createPropertyBag();e.setProperty("name",c);e.setProperty("itemcount",d.itemCount);e.setProperty("foldercount",d.folderCount);e.setProperty("livemarkcount",d.livemarkCount);e.setProperty("separatorcount",d.separatorCount);c=this.service_.createEventItem("http://www.mozilla.org/metrics","bookmarklocation");c.properties=e;b.appendChild(c)};
